### ISSUE TITLE
unable to get public key for signed JWT - no Google OAuth2 provider key found for GCE role

### ISSUE THREAD

**Issue by zarko-a** [hashicorp/vault-plugin-auth-gcp#116] opened 2021-08-25 23:03 UTC
I've configured a GCP authentication and a GCE role in Vault 1.7.2 with the following commands:

```
vault auth enable gcp

vault write auth/gcp/config credentials=@/path/to/file/creds.json

vault write auth/gcp/role/test-gce-role \
    type="gce" \
    policies="test-role-db-viewer" \
    bound_projects="dev" \
    bound_zones="us-east1-b" \
    bound_service_accounts="XXXX-compute@developer.gserviceaccount.com"
```

Then I attempted to login from a GCP (Ubuntu) instance with the following command:
` vault login -method=gcp role="test-gce-role" service_account="XXXX-compute@developer.gserviceaccount.com" jwt_exp="15m"`

But ended up with an error:
```
Error authenticating: Error making API request.

URL: PUT https://vault-host/v1/auth/gcp/login
Code: 400. Errors:

* unable to get public key for signed JWT: unable to get public key "XXXXXXXXXXX" for JWT subject "XXXX-compute@developer.gserviceaccount.com": no Google OAuth2 provider key found for GCE role
```

Any advice? 
I don't see an option to configure the JWT validation endpoint in Vault. Could this be a bug?

Service account for the instance has access to the APIs and is also assigned `roles/iam.serviceAccountTokenCreator` . 

Service account for the Vault Server (responsible for validating the JWT) has a custom role per the [official guide](https://www.vaultproject.io/docs/auth/gcp), with the following permissions:
```
iam.serviceAccounts.get
iam.serviceAccountKeys.get
compute.instances.get
compute.instanceGroups.list
```

**Comment by bodji** [comment] 2021-09-02 07:45
I'm having the exact same issue !

**Comment by bodji** [comment] 2021-09-03 14:20
I looked again today, but I can't find where the problem is, maybe @emilymye you have an idea ? 

Thanks a lot !

**Comment by tush-tr** [comment] 2022-09-14 21:12
I would suggest you to generate JWT using gcloud/ google api

```sh
$ vault auth enable gcp
$ vault write auth/gcp/config \
    credentials=@/path/to/credentials.json
```

**Comment by NoahJinnn** [comment] 2023-09-28 14:27
You might want to have a look on this tutorial: https://support.hashicorp.com/hc/en-us/articles/9742437671827-Authenticating-to-Vault-using-Google-Cloud-IAM-service-accounts

I successfully login to my vault with gcp.

**Comment by raymonstah** [comment] 2024-01-02 19:04
Hey @zarko-a, are you still running into this issue on the latest version of Vault?

**Comment by zarko-a** [comment] 2024-01-02 19:08
@raymonstah Unfortunately, I no longer use Vault at my new gig. So, I don't have any additional info.

**Comment by raymonstah** [comment] 2024-01-02 19:10
No worries, thanks for getting back to me so quickly.

I'm going to close this issue, if anyone else is running into the same problem, feel free to open a new issue!

**Closed by raymonstah** 2024-01-02 19:10 UTC

**Comment by fancybear-dev** [comment] 2024-10-19 14:24
Adding a comment here to potentially help others seeing the same error.

We are currently observing this same issue.

The reason this occurs for us, is because the Google API itself is returning different responses suspectedly based on routing. It seems like a CDN issue to us or something along those lines. 

What is happening;

When a token is generated, a public key is used that is associated with the service account. This key is retrieved via;

https://www.googleapis.com/service_accounts/v1/metadata/x509/computeXXXXX.iam.gserviceaccount.com?alt=json

Service accounts, can have more than one public key associated with it - this is where our issue comes in.

We are currently unable to authenticate to Vault, because Google is returning different responses with different public keys. 

One response contains a single public key, whilst the other contains two. The error is correct, as when two are returned, the first is used. The public keys don't match -> error. The public key is used both when creating a JWT token, as well as when it is verified (e.g. by Vault server).

We have other service accounts that also have multiple public keys, but where we do not have this inconsistency error.

I have confirmed that even different datacenter locations in Google Cloud itself, the response differs. I find this highly unusual and we have never seen this before in our years of extensive Google Cloud API use. We're talking about the exact same API call that is returning a different response - purely (suspectedly) based on routing. Now we don't know how routing is evaluated, but we are certain it is at cause. Some backends are not in sync as they should be. I reported this to Google, but have not received any response yet. 

It is my understanding that it's not trivial to fix this, both the JWT creator as well as the validator must both have safeguards to evaluate all available public keys for this to be properly fixed. It's likely easier to just recreate the service account affected or even centralizing network flows to guarantee consistent routing...  especially considering that given how little people have this issue, it's too niche to perform root cause fixes. This wouldn't even been an issue if Google was returning consistent responses as well.
