### ISSUE TITLE
GCP July 2021 deadline for projects.serviceAccounts/signJwt deprecation

### ISSUE THREAD

**Issue by wimo7083** [hashicorp/vault-plugin-auth-gcp#106] opened 2021-04-01 18:25 UTC
#100  mentions this but this ticket is regarding the effort required to make this change prior to July 2021.

I started looking into it and I ran into some questions that indicated I should ask for guidance, as it appears this change would require modifying the public interface.

1. Template is obtained from github.com/hashicorp/go-gcp-common
```diff
+++ b/vendor/github.com/hashicorp/go-gcp-common/gcputil/iam_admin.go
-       ServiceAccountTemplate    = "projects/%s/serviceAccounts/%s"
+       ServiceAccountTemplate    = "projects/-/serviceAccounts/%s"
```

2. This method requires iam.Service, which to my golang newbiness would break the API by changing to iamcredentials.Service, and there's a rabbit hole that begins at `plugin/path_login_test.go` and ends up in a few locations.
```golang
func ServiceAccountLoginJwt(
      iamClient *iam.Service, exp time.Time, aud, project, serviceAccount string) (*iam.SignJwtResponse, er
 ```
 
3. There's ~ 12 places the `"google.golang.org/api/iam/v1` is used and frankly, I'm not comfortable doing a find and replace as it doesn't appear the entire API is just deprecated. So I'm not really sure what would be best here.
 
 If you could offer some guidance I'd be happy to submit a patch.

**Comment by kalafut** [comment] 2021-04-14 03:59
@wimo7083 Thanks, we are actively looking into this issue.

**Comment by catsby** [comment] 2021-04-23 18:00
Hello @wimo7083! Thank you again for opening this issue. We have a work-in-progress fix started in https://github.com/hashicorp/vault-plugin-auth-gcp/pull/108. For now though I'm going to consider this issue a duplicate of https://github.com/hashicorp/vault-plugin-auth-gcp/issues/100 and kindly ask you to track either #100 or #108 for resolution. 

Thanks!

**Closed by catsby** 2021-04-23 18:00 UTC
